module.exports = {
    Priority: {
        Literal: 1,
        Comment: 2,
        ContentChange: 3,
        Table: 4,
        FullLine: 5,
        LiteralFormat: 6,
        Format: 7,
        Footnote: 8,
        Last: 9
    },
    AllowedLanguages: [
        'basic',
        'cpp',
        'csharp',
        'css',
        'erlang',
        'go',
        'html',
        'java',
        'javascript',
        'json',
        'kotlin',
        'lisp',
        'lua',
        'markdown',
        'objectivec',
        'perl',
        'php',
        'powershell',
        'python',
        'ruby',
        'rust',
        'sh',
        'sql',
        'swift',
        'typescript',
        'xml'
    ].sort((a,
b) => b.length - a.length),
    SelfClosingTags: [
        'img',
        'br',
        'hr',
        'area',
        'base',
        'basefont',
        'input',
        'link',
        'meta'
    ],
}