module.exports = {
    Priority: {
        Literal: 1,
        Comment: 2,
        ContentChange: 3,
        Heading: 4,
        Macro: 5,
        Footnote: 6,
        Div: 7,
        ChildParser: 8,
        LiteralFormat: 9,
        Format: 10,
        Last: 11
    },
    AllowedLanguages: [
        'basic',
        'cpp',
        'csharp',
        'css',
        'erlang',
        'go',
        'html',
        'java',
        'javascript',
        'json',
        'kotlin',
        'lisp',
        'lua',
        'markdown',
        'objectivec',
        'perl',
        'php',
        'powershell',
        'python',
        'ruby',
        'rust',
        'sh',
        'sql',
        'swift',
        'typescript',
        'xml'
    ].sort((a,
b) => b.length - a.length),
    SelfClosingTags: [
        'img',
        'br',
        'hr',
        'area',
        'base',
        'basefont',
        'input',
        'link',
        'meta'
    ],
}